# Generated by Django 2.2 on 2022-07-29 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='teg',
            field=models.CharField(default=None, max_length=100, verbose_name='Тег'),
        ),
        migrations.AlterField(
            model_name='news',
            name='title',
            field=models.CharField(max_length=1000, verbose_name='Название'),
        ),
    ]
