# Generated by Django 2.2 on 2022-07-29 16:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app_users', '0002_auto_20220729_1010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='teg',
            field=models.CharField(blank=True, default=None, max_length=100, verbose_name='Тег'),
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password2', models.CharField(max_length=100)),
                ('tel', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, unique=True)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('type_user', models.CharField(blank=True, max_length=300)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
