# Generated by Django 2.2 on 2022-07-30 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_users', '0003_auto_20220729_1958'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='password2',
        ),
    ]
