# Generated by Django 2.2 on 2022-08-03 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_users', '0004_remove_profile_password2'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'permissions': (('can_publish', 'Может публиковать'),), 'verbose_name': 'новость', 'verbose_name_plural': 'новость'},
        ),
        migrations.AddField(
            model_name='news',
            name='flag_publication',
            field=models.CharField(choices=[('p', 'published'), ('np', 'not published'), ('pp', 'pending publication')], default='np', max_length=300),
        ),
        migrations.AddField(
            model_name='profile',
            name='news_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='profile',
            name='type_user',
            field=models.CharField(blank=True, choices=[('ordinary', 'ordinary'), ('expectation', 'expectation'), ('verified', 'verified')], default='ordinary', max_length=300),
        ),
    ]
