# Generated by Django 2.2 on 2022-08-03 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_users', '0005_auto_20220803_1226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='flag_publication',
            field=models.CharField(blank=True, choices=[('p', 'published'), ('np', 'not published'), ('pp', 'pending publication')], default='np', max_length=300),
        ),
    ]
