# Generated by Django 2.2 on 2022-08-03 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_users', '0006_auto_20220803_1237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='flag_publication',
            field=models.CharField(blank=True, choices=[('published', 'published'), ('not published', 'not published'), ('pending publication', 'pending publication')], default='np', max_length=300),
        ),
    ]
