# Generated by Django 2.2 on 2022-08-03 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_users', '0007_auto_20220803_1238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='flag_publication',
            field=models.CharField(blank=True, choices=[('published', 'published'), ('not published', 'not published'), ('pending publication', 'pending publication')], default='not published', max_length=300),
        ),
        migrations.AlterField(
            model_name='profile',
            name='news_count',
            field=models.IntegerField(),
        ),
    ]
