# Generated by Django 2.2 on 2022-08-03 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_users', '0008_auto_20220803_1810'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='news_count',
            field=models.IntegerField(default=0),
        ),
    ]
