# Generated by Django 2.2 on 2022-07-14 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_news', '0002_auto_20220714_1524'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='flag',
            field=models.BooleanField(choices=[('a', 'actively'), ('n', 'not active')], default='n'),
        ),
    ]
